// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbmuY5km8CB3wnJ_8OOSVkSaK-jqv0E-c',
    appId: '1:694212447227:web:15dce5ff954c614823195e',
    messagingSenderId: '694212447227',
    projectId: 'toilet-locator-b3a78',
    authDomain: 'toilet-locator-b3a78.firebaseapp.com',
    storageBucket: 'toilet-locator-b3a78.firebasestorage.app',
    measurementId: 'G-NEH5N0EWB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlleKvmI-IqjqV1RFz9PlAxv3Szy4Ff5o',
    appId: '1:694212447227:android:72c380df6a2698a023195e',
    messagingSenderId: '694212447227',
    projectId: 'toilet-locator-b3a78',
    storageBucket: 'toilet-locator-b3a78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw-2_ynUTPruNtglEwBkLF-hbq1qLAeJo',
    appId: '1:694212447227:ios:e967a034785e7e1323195e',
    messagingSenderId: '694212447227',
    projectId: 'toilet-locator-b3a78',
    storageBucket: 'toilet-locator-b3a78.firebasestorage.app',
    iosBundleId: 'com.example.toiletLocator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw-2_ynUTPruNtglEwBkLF-hbq1qLAeJo',
    appId: '1:694212447227:ios:e967a034785e7e1323195e',
    messagingSenderId: '694212447227',
    projectId: 'toilet-locator-b3a78',
    storageBucket: 'toilet-locator-b3a78.firebasestorage.app',
    iosBundleId: 'com.example.toiletLocator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbmuY5km8CB3wnJ_8OOSVkSaK-jqv0E-c',
    appId: '1:694212447227:web:b252ba95e877fbc223195e',
    messagingSenderId: '694212447227',
    projectId: 'toilet-locator-b3a78',
    authDomain: 'toilet-locator-b3a78.firebaseapp.com',
    storageBucket: 'toilet-locator-b3a78.firebasestorage.app',
    measurementId: 'G-LXEH67L249',
  );

}